// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxufbwrahxcuxjojwnid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dWZid3JhaHhjdXhqb2p3bmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjMwMTQsImV4cCI6MjA2MTM5OTAxNH0.F4ggE6f0V9kz45J9ke1i5_W7AChF37lk6OTD5ILk7Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);